# Change these first
owner: hjstrauss # Your GitHub organization or username, where this repository lives
repo: MonitorMySites # The name of this repository

sites:
  - name: HJStrauss
    url: https://www.hjstrauss.de
  - name: Reime ohne Sinn und Verstand
    url: https://www.reimeohnesinnundverstand.de
  - name: Griffo
    url: https://www.griffo.de
  - name: LM Bogen WSV
    url: https://www.lmbogenwsv.de
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /MonitorMySites
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**MonitorMySites** is based on Upptime (the open-source uptime monitor and status page, powered entirely by GitHub) and monitors several websites."
  introMessage: This is a status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
